### PR TITLE
mob dead state tweaks

### LINKED ISSUE #145: Mob still can move while in crit/dead state
Also there is no move code in content which could prohibit mob from moving, i guess move code is in engine

### LINKED ISSUE #158: Mob doesn't fall (rotate 90 degrees) on the ground
(it's now separate issue)
Should make appearance visualizer for that

### PR DESCRIPTION
**Pull request by Injazz**
~~well, it SHOULD make mob rotate on death, but it doesn't, i have no idea why~~

- Blocks character movement in crit/death
- rotates character ~~360noscope~~ 90 degrees to convince you it's lying down when dead

resolves #145
resolves #158
related to #115

### CODE REVIEW

**Comment by Injazz** [comment]
Now crit and dead mob can't move

**Comment by Injazz** [comment]
also submodule update

**Comment by Injazz** [comment]
FUCK

**Comment by Injazz** [comment]
okay it's done

**Comment by clusterfack** [comment]
This has so many problems

1. The movement system still doesnt check the movement blocker with this change, this just manually sets movement to disabled
2. We already have a clientside component using species netid, it's used for the UI so making a shared component isnt appropriate here
3. The change to incorporate appearance class means that every single mob that can exist needs to use appearance class or game will error

And a few other things, it's not your fault but these should have been caught in review.

**Comment by PJB3005** [comment]
> The movement system still doesnt check the movement blocker with this change, this just manually sets movement to disabled

That's because movement is implemented in engine right now so there's no real alternative.

> We already have a clientside component using species netid, it's used for the UI so making a shared component isnt appropriate here

Minor issue though it should be fixed yes.

> The change to incorporate appearance class means that every single mob that can exist needs to use appearance class or game will error

Again a minor issue I'd say.

**Comment by clusterfack** [comment]
None of those are minor issues, and I'm 80% sure now that you merged in this PR without saying anything to me because you want to lock us into your appearance "solution"

**Comment by PJB3005** [comment]
Yes, yes they are minor issues.

> I'm 80% sure now that you merged in this PR without saying anything to me because you want to lock us into your appearance "solution"

1. yes, it is a solution that works.
2. yes, I personally believe it is the best solution.
3. why the hell does this have to be a "you vs me" deal as if I have an evil plan?

**Comment by clusterfack** [comment]
Because you didnt think to say anything to me about a PR that massively changes how a component I created worked because it implemented some dumb solution you've set your heart on. 

Even though this PR has many issues you just rubber stamped it in. 90% of the changes in this PR need to be reworked, and you should have known that or looked to find out.

**Comment by PJB3005** [comment]
> Because you didnt think to say anything to me about a PR that massively changes how a component I created worked because it implemented some dumb solution you've set your heart on.

Saying it "massively" changes the component is hyperbole and you know it.

And no, I do not think it's "some dumb solution", but we already established we disagree on that in Discord.

If you want me to notify you when a PR related to your code comes up that's absolutely fine with me in the future, but still there is no reason to be this violated by it.

> Even though this PR has many issues you just rubber stamped it in

I disagree that it has "so many issues". The only real significant issue is the movement thing, the rest is absolutely a "nice to have if somebody wants to improve it". And even the movement thing is relatively easy to fix when somebody moves movement into content.

**Pull request merged**
