### PR TITLE
Storage Component (toolboxes, backpacks, etc)

### LINKED ISSUE #53: Storage System
We have the very basics of this system already implemented through the 'item' component and the container type.

The storage system will function primarily via two components. Storage and Storeable. Storeable should be the new parent type of item, item being a subtype that can specifically be picked up by mobs.

Storage at this point could either use a ingame GUI or a window. Preferrably a window since we haven't nailed out all the details of 3D and sprites and an ingame GUI that can handle arbitrary sizes of storage is overkill at this point. Ideally it should have something like a define that shows the maximum object size that can be placed inside and the maximum total volume it can hold.

Storeable primarily should have an object size, and whatever other considerations you want to give it.

### PR DESCRIPTION
**Pull request by clusterfack**
image

Closes #53
## Summary
Adds a component for containers that store entities, which defines a storage capacity that it can hold.

Entities that can be stored have the storeable component, and the item component type is a subtype of the storeable component now which defines stored size.

This is heavily based on the entity spawn panel which was made by @PJB3005, who on top of that gave me metric tons of help working with godot's UI editor so much thanks to him wouldn't have been possible without him.

### Status
This is about 100% completed. The container works exactly as it should, both with entering and removal of items. The primary issues that exist right now are
- I need to change up what causes the UI to open itself after fixing the above, as described in the prior bullet point

### CODE REVIEW

**Comment by clusterfack** [comment]
This PR now fixes the use interaction not ever working, for both the active held item bound key as well as left clicking on the active hand in the hands gui. All it requires now is some minor tweaks to when the UI opens and it's completely finished.

**Comment by clusterfack** [comment]
Alright this is finished, the only issue it has is that I have trouble reopening the UI window when it closes, and I get like 3 different various errors normally related to scene control or missing element references.

**Comment by PJB3005** [comment]
Gonna need a way to load tscn files from content WITHOUT loading GodotSharp.

**Comment by clusterfack** [comment]
Fixed

**Pull request merged**
