### PR TITLE
Power System (Complete)

### LINKED ISSUE #24: Power System
The power system fundamentally works based on a few component

- Transfer - in ss13 terms these are wires, these entities connect to each other and to nodes to make up the powernet
- Nodes - This is a component that controls connecting to the powernet through wires
- Device - devices use power and either draw power from the node (powernet) or from power providers (eg apc) depending on their settings
- Provider - provides power to devices at a range
- Storage - internally stores power drawn from the node, either for use by other components (internal battery for apc) or through a setting to distribute back to the powernet (smes)
- Generator - puts power into the powernet that other sources can draw from

And the powernet itself which gathers up all the power supplied, dishes it out to devices and then finally uses extra stored power if necessary else charges the storage devices

### PR DESCRIPTION
**Pull request by clusterfack**
This establishes a powernet system for the base game. 
Fixes #24 

This system isn't fully tested due to a spawning system bug, however I've fixed every exception that has come up during testing and it compiles and runs and each individual entity spawns without any problem.

**Components**
- Power Transfer - creates wirenet
- Node - connects to wirenet (components who needs this generate it themselves)
- Device - uses power
- Power Provider (device subtype) - broadcasts power to devices
- Power Generator - creates power
- Power Storage - stores power, can give back to powernet or supply device internally depending on settings

**Classes**
- Powernet - controls wirenet and distribution energy supply to and from during its Update()

**Entity System**
- Powernet entity system - regenerates dirty powernets (when a wire gets removed) on the next update() tick, and then calls update() on the necessary powernets

**Prototypes**
- Wire - Power Transfer
- Power Generator - Node + Power Generator
- APC - Node + Power Provider (+ storage)
- Wired Machine - Node + Device
- Wireless Machine - Device
- SMES - Node + Storage (chargepowernet set on)

### CODE REVIEW

**Comment by Silvertorch5** [comment]
[forthebadge](http://forthebadge.com)

**Comment by clusterfack** [comment]
Pls wait to merge this until I add shutdown functions on all the components and can do a small bit of testing with the spawn entity fix

**Comment by clusterfack** [comment]
I didn't add "shutdown" and "startup" functionality like I said I was going to, but I added the functionality that was my intention to add all along which was onremove() which is necessary for this to function properly with removal of entities. I still need to do some testing however with a spawnentity fix which I'm tackling next.

**Comment by clusterfack** [comment]
Alright, tested and removed about four bugs, no more could be found

**Pull request merged**
